version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    ports:
      - "80:80"
    restart: always
  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: app_server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
