version: "3"
services:
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
  nginx:
    restart: always
    build:
      context: ./nginx
  server:
    build:
      context: ./server
    container_name: app_server
    volumes:
      - ./server:/app
    command:
      - ""
    ports:
      - "8080:8080"